baseURL: https://maximilian-pierzyna.de/
languageCode: de
title: Maximilian Pierzyna
theme: hugo-PaperMod
publishDir: docs

# Language settings
DefaultContentLanguage: de
DefaultContentLanguageInSubdir: true
languages:
  de:
    contentDir: content/de
    languageName: ":de:"
    weight: 1
  en:
    contentDir: content/en
    languageName: ":uk:"
    weight: 2

# Disable all 3rd party functionalities
privacy:
  disqus:
    disable: true
  googleAnalytics:
    disable: true
  instagram:
    disable: true
  twitter:
    disable: true
  vimeo:
    disable: true
  youtube:
    disable: true

# Site params
params:
  displayFullLangName: true
  profileMode:
    enabled: true
    subtitle: subtitle
    imageUrl: "/img/foto_me.jpg"
    imageWidth: 300
    imageHeight: 300
    buttons:
      # Button names can be i18n id to be translated on language switch
      - name: cv
        url: "/files/Maximilian_Pierzyna_CV.pdf"
      - name: contact
        url: "contact"

  # Custom CSS
  custom_css: 
    - "css/halfmoon/halfmoon_hm-11.css"
    - "css/manual.css"

  # Custom JS (currently not in use)
  #custom_js: 
    #- "js"



