baseURL: https://maximilian-pierzyna.de/
languageCode: en
title: Maximilian Pierzyna
theme: hugo-PaperMod
publishDir: docs

# Language settings
#DefaultContentLanguage: en
#DefaultContentLanguageInSubdir: true
#languages:
  #de:
    #contentDir: content/de
    #languageName: ":de:"
    #weight: 1
  #en:
    #contentDir: content/en
    #languageName: ":uk:"
    #weight: 2

# Disable all 3rd party functionalities
privacy:
  disqus:
    disable: true
  googleAnalytics:
    disable: true
  instagram:
    disable: true
  twitter:
    disable: true
  vimeo:
    disable: true
  youtube:
    disable: true

# Site params
params:
  displayFullLangName: true
  profileMode:
    enabled: true
    subtitle:  "curious about modelling atmospheric turbulence 💨 with data-driven methods 📊"
    imageUrl: "/img/foto_me.jpg"
    vcardQrUrl: "/img/vcard_qr.png"
    imageWidth: 300
    imageHeight: 300
    buttons:
      # Button names can be i18n id to be translated on language switch
      - name: Research
        url: "/research"
      - name: CV (PDF)
        url: "/files/Maximilian_Pierzyna_CV.pdf"
      - name: Contact
        url: "contact"

  socialIcons:
    - name: Linkedin
      url: https://www.linkedin.com/in/maximilian-pierzyna-b6540a143
    - name: Github
      url: https://github.com/mpierzyna
    - name: GoogleScholar
      url: https://scholar.google.com/citations?user=8puaR54AAAAJ
    - name: ResearchGate
      url: https://www.researchgate.net/profile/Maximilian-Pierzyna

  # Custom CSS
  custom_css: 
    - "css/halfmoon/halfmoon_hm-11.css"
    - "css/manual.css"

  # Custom JS (currently not in use)
  custom_js: 
    - "js/custom.js"


